WARNING:tensorflow:From /usr/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
2018-08-29 16:27:21.174120: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: FMA
/usr/lib/python3.5/site-packages/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
expected positive_prediction [[[ 1.]
  [ 1.]
  [ 1.]
  ..., 
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  ..., 
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  ..., 
  [ 1.]
  [ 1.]
  [ 1.]]

 ..., 
 [[ 1.]
  [ 1.]
  [ 1.]
  ..., 
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  ..., 
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  ..., 
  [ 1.]
  [ 1.]
  [ 1.]]]
expected negativee_prediction [[[ 0.]
  [ 0.]
  [ 0.]
  ..., 
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  ..., 
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  ..., 
  [ 0.]
  [ 0.]
  [ 0.]]

 ..., 
 [[ 0.]
  [ 0.]
  [ 0.]
  ..., 
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  ..., 
  [ 0.]
  [ 0.]
  [ 0.]]

 [[ 0.]
  [ 0.]
  [ 0.]
  ..., 
  [ 0.]
  [ 0.]
  [ 0.]]]
host_positive_prediction (65, 65, 1) [[[ 0.50000709]
  [ 0.50000709]
  [ 0.50260347]
  ..., 
  [ 0.50265771]
  [ 0.50205159]
  [ 0.50298661]]

 [[ 0.50000709]
  [ 0.50000709]
  [ 0.49575859]
  ..., 
  [ 0.50031716]
  [ 0.49735144]
  [ 0.50109899]]

 [[ 0.50136876]
  [ 0.50032216]
  [ 0.50158751]
  ..., 
  [ 0.49729872]
  [ 0.50330186]
  [ 0.49918023]]

 ..., 
 [[ 0.49354994]
  [ 0.50732559]
  [ 0.50571424]
  ..., 
  [ 0.50173318]
  [ 0.504215  ]
  [ 0.50213885]]

 [[ 0.49809965]
  [ 0.49944854]
  [ 0.50399131]
  ..., 
  [ 0.50285989]
  [ 0.49677882]
  [ 0.50488746]]

 [[ 0.50573283]
  [ 0.49545416]
  [ 0.493853  ]
  ..., 
  [ 0.49630803]
  [ 0.50230944]
  [ 0.49968526]]]
host_negative_prediction (65, 65, 1) [[[ 0.50211501]
  [ 0.49831897]
  [ 0.50040323]
  ..., 
  [ 0.50043082]
  [ 0.50283754]
  [ 0.50407374]]

 [[ 0.50016493]
  [ 0.49914339]
  [ 0.50225824]
  ..., 
  [ 0.50017214]
  [ 0.49826664]
  [ 0.49794307]]

 [[ 0.49567473]
  [ 0.50542384]
  [ 0.49170181]
  ..., 
  [ 0.4993867 ]
  [ 0.50253832]
  [ 0.50455821]]

 ..., 
 [[ 0.48351052]
  [ 0.50613928]
  [ 0.49969208]
  ..., 
  [ 0.4992885 ]
  [ 0.50600833]
  [ 0.50222653]]

 [[ 0.50002521]
  [ 0.49843931]
  [ 0.49880373]
  ..., 
  [ 0.50224543]
  [ 0.49938717]
  [ 0.49906626]]

 [[ 0.49614733]
  [ 0.50510585]
  [ 0.50160897]
  ..., 
  [ 0.49632576]
  [ 0.50084281]
  [ 0.50166678]]]
ncs_positive_prediction (274625,) [  5.00000000e-01   5.00000000e-01   5.02441406e-01 ...,  -5.90209961e-02
  -1.06875000e+02  -5.22155762e-02]
ncs_negative_prediction (274625,) [ 0.50195312  0.49804688  0.50048828 ..., -0.21350098         nan
  0.00088644]
Traceback (most recent call last):
  File "./compare_inference_on_host_and_ncs.py", line 68, in <module>
    ncs_positive_prediction.shape))
Exception: shape mismatch between host [(65, 65, 1)] and ncs [(274625,)]
